CREATE DATABASE sampledb
    WITH 
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

\c sampledb


CREATE TABLE PERSON (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);