CREATE DATABASE ggj2020
    WITH 
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

\c ggj2020


CREATE TABLE Game (
    ID SERIAL NOT NULL,
    CREATED timestamp  NOT NULL,
    URI VARCHAR(255) NOT NULL,
    CLOSED BIT,
    PRIMARY KEY(ID)

);

CREATE TABLE Player (
    ID SERIAL NOT NULL,
    GAME_ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TOKEN VARCHAR(255),
    PRIMARY KEY(ID),
    FOREIGN KEY(GAME_ID) REFERENCES Game(ID)
);